---
name: iris-erp-frontend-web-app-prod
services:
  app:
    container_name: iris-erp-frontend-web-app-prod-c
    image: iris-erp-frontend-web-app-prod-i:1.0
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8053:80'
# docker image tag iris-erp-frontend-web-app-prod-i:1.0 silveira42/iris-erp-frontend-web-app:1.0
# docker image tag iris-erp-frontend-web-app-prod-i:1.0 silveira42/iris-erp-frontend-web-app:latest
# docker push silveira42/iris-erp-frontend-web-app:1.0
# docker push silveira42/iris-erp-frontend-web-app:latest
